name: Update Packagist

on:
  push:
    tags: ['v*']

jobs:
  update:
    runs-on: ubuntu-latest
    name: Notify Packagist

    steps:
      - name: Trigger package update
        run: |
          curl -sf -XPOST -H'content-type:application/json' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
            -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}'
